export { default as handleAddition } from "./addition";
export { default as handleMultiplication } from "./multiplication";
export { default as handleInput } from "./input";
export { default as handleOutput } from "./output";
export { default as handleJumpIfTrue } from "./jumpIfTrue";
export { default as handleJumpIfFalse } from "./jumpIfFalse";
export { default as handleLessThan } from "./lessThan";
export { default as handleEquals } from "./equals";
export { default as handleAdjustRelativeBase } from "./adjustRelativeBase";
